version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whosaidit-frontend-prod
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/app
    #   - /app/node_modules