services:
  postgres:
    container_name: postgres-wsi
    image: postgres:16.0
    environment:
      POSTGRES_DB: whosaidit-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - webapp
    restart: unless-stopped

  backend:
    build: .
    container_name: whosaidit-backend
    image: whosaidit-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whosaidit-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - webapp

networks:
  webapp:
    driver: bridge

volumes:
  postgres: