spring:
  application:
    name: "WhoSaidIt Backend"
  profiles:
    default: "dev"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

springdoc:
  swagger-ui:
    path: "/api-docs"
    operations-sorter: method

server:
  error:
    include-binding-errors: always
    include-message: always