spring:
  application:
    name: "WhoSaidIt Backend"
  profiles:
    default: "dev"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  error:
    include-binding-errors: always
    include-message: always