spring:

  application:
    name: "WhoSaidIt Backend"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default to dev if prod is not explicitly set

  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 90MB

  mail:
    host: "smtp.sendgrid.net"
    port: 587
    username: "apikey"
    password: ${SENDGRID_API_KEY} # This secret must be set as an env variable in the execution environment
    protocol: "smtp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  swagger-ui:
    path: "/api-docs"
    operations-sorter: method

server:
  error:
    include-binding-errors: always
    include-message: always

jwt:
  # This secret must be set as an environment variable in the execution environment.
  # For developers, define this variable as any base64 encoded string
  secret: ${WHOSAIDIT_JWT_SECRET}