name: Backend Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:backend"
        file: ./Dockerfile
        push: true
        tags: nathan7934/whosaidit-backend:latest