name: Frontend AWS EC2 CD

on:
  workflow_run:
    workflows: ["Frontend Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, frontend]

    steps:
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the Docker image
      run: docker pull nathan7934/whosaidit-frontend:latest

    - name: Delete old Docker container
      run: docker rm -f whosaidit-frontend-container || true

    - name: Run new Docker container
      run: docker run -d -p 80:3000 --name whosaidit-frontend-container nathan7934/whosaidit-frontend